import{Environment}from"./environment";import{createBuiltins}from"./builtins";import type{Program,Stmt,Expr}from"../lang/ast";import type{RuntimeGame}from"../runtime/game";
class Ret{constructor(public value:unknown){}}class Break{}
export class Interpreter{
 private env=new Environment();private funcs=new Map<string,any>();private builtins:Map<string,(args:unknown[])=>unknown>;
 constructor(private game:RuntimeGame){this.builtins=createBuiltins(game)}
 run(p:Program){for(const s of p.body)if(s.kind==="function")this.funcs.set(this.norm(s.name),s);for(const s of p.body)if(!["function","hook","actor","collision"].includes(s.kind))this.exec(s)}
 exec(s:Stmt):unknown{switch(s.kind){case"assign":{const v=this.eval(s.value);const t:any=s.target;if(t.kind==="variable"){const old=s.op==="="?0:this.env.get(t.name);this.env.set(t.name,s.op==="="?v:s.op==="+="?this.add(old,v):Number(old)-Number(v));return v}if(t.kind==="member"){const o:any=this.eval(t.object);const old=o[t.property];o[t.property]=s.op==="="?v:s.op==="+="?this.add(old,v):Number(old)-Number(v);return o[t.property]}throw new Error("Destino de atribuição inválido.")}case"expr":return this.eval(s.expr);case"say":{const v=this.interpolate(String(this.eval(s.expr)));this.game.say(v);return v}case"if":return this.execBlock(this.truth(this.eval(s.condition))?s.thenBranch:s.elseBranch);case"while":{let n=0;while(this.truth(this.eval(s.condition))){if(++n>100000)throw new Error("Loop interrompido por segurança.");try{this.execBlock(s.body)}catch(e){if(e instanceof Break)break;throw e}}return null}case"repeat":{const n=Math.max(0,Math.trunc(Number(this.eval(s.count))));if(n>100000)throw new Error("Repetição muito grande.");for(let i=0;i<n;i++)try{this.execBlock(s.body)}catch(e){if(e instanceof Break)break;throw e}return null}case"foreach":{const xs=this.eval(s.list);if(!Array.isArray(xs))throw new Error("para cada precisa de uma lista.");for(const x of xs){this.env.set(s.name,x);try{this.execBlock(s.body)}catch(e){if(e instanceof Break)break;throw e}}return null}case"return":throw new Ret(s.value?this.eval(s.value):null);case"break":throw new Break();case"ask":{const q=String(this.eval(s.expr));const a=typeof window==="undefined"?"":window.prompt(q)??"";this.env.set(s.name,a);return a}case"draw":return this.game.drawStatement(s,(e:Expr)=>this.eval(e));case"noop":return this.game.handleNoop(s.name,s.args.map(a=>this.eval(a)));default:return null}}
 private execBlock(b:Stmt[]){let r:null|unknown=null;for(const s of b)r=this.exec(s);return r}
 eval(e:Expr):any{switch(e.kind){case"literal":return e.value;case"variable":return this.resolve(e.name);case"list":return e.items.map(x=>this.eval(x));case"member":return(this.eval(e.object)as any)?.[e.property];case"unary":{const v=this.eval(e.expr);return e.op==="!"||this.norm(e.op)==="nao"?!this.truth(v):e.op==="-"?-Number(v):Number(v)}case"call":{const args=e.args.map(a=>this.eval(a));if(e.callee.kind!=="variable")throw new Error("Chamada inválida.");const n=this.norm(e.callee.name),b=this.builtins.get(n);if(b)return b(args);const f=this.funcs.get(n);if(!f)throw new Error(`Função "${e.callee.name}" não existe.`);const prev=this.env;this.env=new Environment(prev);f.params.forEach((p:string,i:number)=>this.env.set(p,args[i]??null));try{this.execBlock(f.body);return null}catch(x){if(x instanceof Ret)return x.value;throw x}finally{this.env=prev}}case"binary":{const op=this.norm(e.op),a=this.eval(e.left);if(op==="e"||e.op==="&&")return this.truth(a)&&this.truth(this.eval(e.right));if(op==="ou"||e.op==="||")return this.truth(a)||this.truth(this.eval(e.right));const b=this.eval(e.right);switch(e.op){case"+":return this.add(a,b);case"-":return Number(a)-Number(b);case"*":return Number(a)*Number(b);case"/":if(Number(b)===0)throw new Error("Divisão por zero.");return Number(a)/Number(b);case"//":if(Number(b)===0)throw new Error("Divisão por zero.");return Math.floor(Number(a)/Number(b));case"%":return Number(a)%Number(b);case"^":return Number(a)**Number(b);case"==":return Object.is(a,b);case"!=":return !Object.is(a,b);case"<":return a<b;case"<=":return a<=b;case">":return a>b;case">=":return a>=b;default:throw new Error("Operador desconhecido.")}}}}
 private resolve(n:string){if(this.env.has(n))return this.env.get(n);if(this.game.hasActor(n))return this.game.getActor(n);const k=this.norm(n),colors=["preto","branco","cinza","vermelho","laranja","amarelo","verde","ciano","azul","roxo","rosa","marrom","bege","verde_claro","azul_claro","transparente"];if(colors.includes(k))return k;if(k==="verdadeiro")return true;if(k==="falso")return false;if(k==="nulo")return null;throw new Error(`A variável "${n}" não existe.`)}
 private add(a:any,b:any){return typeof a==="string"||typeof b==="string"?String(a)+String(b):Number(a)+Number(b)}private truth(v:any){return!!v}private norm(v:string){return v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase()}private interpolate(v:string){return v.replace(/\{([^}]+)\}/g,(_,n)=>String(this.resolve(n.trim())))} }